plugins: 
- jekyll-seo-tag
- jekyll-paginate
- jekyll-remote-theme

remote_theme: pages-themes/minimal@v0.2.0

<a href="/other_pages/user_manual.md">User Manual</a>

title: HAZEL
#logo: /assets/img/logo.png
description: A pilot generative AI assistant for guidance authors



