plugins: 
- jekyll-seo-tag
- jekyll-paginate
- jekyll-remote-theme

remote_theme: pages-themes/minimal@v0.2.0

title: HAZEL
#logo: /assets/img/logo.png
description: A pilot generative AI assistant for guidance authors



